project:
  type: website
  output-dir: docs

website:
  title: "mark betnel"
  siteurl: "https://markbetnel.com/"
  page-footer:
    left: "Constructed using [Quarto](https://quarto.org), by Mark Betnel. Copyright 2022, all rights reserved unless otherwise noted."
    right:
      - icon: github
        href: https://github.com/itmeson/
      - icon: linkedin
        href: https://linkedin.com/in/markbetnel
  navbar:
    search: true
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: blog/index.qmd
        text: Blog
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-link: true
    smooth-scroll: true
    include-in-header: 
      - counter.html



