---
title: "About"
---

Basically, my career has been about attempting to prove that it's still possible to be a jack of many trades while maintaining a committment to ethics and living well.

Not that anyone's asking me to, but I refuse to work on weapons or surveillance.  That committment led me to study physics and literature as an undergraduate, then to teach high school and go to graduate school in philosophy where I wrote about moral agency and propaganda.  Then when I went back to grad school again, in physics, I chose research projects that were funded outside the defense ecosystem, and focused on my teaching practice and my young family (spouse and newborn).

After my defense, I got a teaching job at Johnson & Wales University in Providence, where I had a very busy two years that included the birth of our second child and teaching **ELEVEN DIFFERENT PREPS** in 6 terms of teaching, out of three different departments.

My wife and I made a difficult choice to leave Rhode Island to move to Seattle so our kids could grow up near their grandparents and cousins, and I took a job at a private high school in Seattle. I'm now in my tenth year in that job, and have taught courses in three departments, created a number of new classes, and helped to develop and launch a new department to offer courses in computational thinking.  I am most proud of increasing enrollment and diversity in our senior physics elective, and of the course I created on the technical and ethical implications of machine learning.

Outside of my main job, I also teach a night course at a local community college, coach youth soccer teams for my kids, am an active member of a Quaker meeting, and I work on writing/education about the uses and implications of technology and issues in education.


