---
title: Unit Tutor
author: "Mark Betnel"
date: "2022-09-14"
categories: [ct, units, physics, js]
---

I've had this idea for years to make a unit-conversion calculator tool for use by students as they are learning dimensional analysis and unit conversion.  I was imagining tile cards showing quantities and conversion factors that they could move around on the page, snapping them into a "picket fence" style grid, flipping them over to form reciprocals, automatically showing unit cancellation, and displaying the result of a unit-ful multiplication with the resulting units at the push of a button.

My hope was that the ease of maniuplating quantities and seeing the results of a calculation would help students better understand things like why multipying "30 meters per second" by "1 minute per 60 seconds" won't tell you how many meters in one minute.

Last spring I finally started to feel like I might be able to create that site, and I spent a significant amount of my release time in May working on a prototype, which is now live at [https://itmeson.github.io/unit-tutor/](https://itmeson.github.io/unit-tutor/).

There are still a lot of issues with the prototype that a "real" engineer might be able to solve quickly, some of which are listed on the github readme for the project, but I feel like I'm ready for a few people to try it out to give me some feedback on more issues and what's worth putting the effort into and what's "okay" as-is.

Issues can be reported using [github issue tracking](https://github.com/itmeson/unit-tutor/issues), or in [this google form](https://docs.google.com/forms/d/e/1FAIpQLSd1qGNh4DS77snyUjXoZ0D9WFxI0gfxRdzaa5-UpSd9pgEbXQ/viewform) which is also linked on the project page.

What I hope to do in the near-term is build a couple of tutorial-style pages that walk users/students through example unit-conversion problems, provide an easy way to make worksheet-style pages that have pre-populated conversion factors and word problems that students can parse to turn into calculations, and an open-calculator mode where the conversion factor tab brings up a drop-down menu of known conversion factors, the quantities tab allows free entry of measured values, and the calculate results can be re-used in more involved multi-step calculations.


